# Generated by Django 4.2.6 on 2023-11-08 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopElectron', '0003_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='img',
            field=models.FileField(default=' ', upload_to='', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, default='0', max_digits=5, verbose_name='Цена'),
        ),
    ]
