# Generated by Django 4.2.6 on 2023-11-08 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopElectron', '0004_product_img_alter_product_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='img',
            field=models.CharField(default=' ', max_length=100, verbose_name='Фото'),
        ),
    ]
