# Generated by Django 4.2.6 on 2023-11-08 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopElectron', '0005_alter_product_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.CharField(default=' ', max_length=150, verbose_name='Описание'),
        ),
    ]
