# Generated by Django 4.2.6 on 2023-11-08 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopElectron', '0006_product_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorii',
            name='url',
            field=models.CharField(default=' ', max_length=50, verbose_name='Ссылка'),
        ),
    ]
