# Generated by Django 4.2.6 on 2023-11-08 05:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopElectron', '0008_alter_categorii_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categorii',
            old_name='url',
            new_name='slug',
        ),
    ]
