# Generated by Django 4.2.6 on 2023-11-22 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopElectron', '0010_product_img2_product_img3_alter_product_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='count',
            field=models.IntegerField(default='0'),
        ),
        migrations.AlterField(
            model_name='product',
            name='img2',
            field=models.CharField(default=' ', max_length=100, verbose_name='Фото2'),
        ),
        migrations.AlterField(
            model_name='product',
            name='img3',
            field=models.CharField(default=' ', max_length=100, verbose_name='Фото3'),
        ),
    ]
