# Generated by Django 4.2.6 on 2023-11-29 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopElectron', '0012_remove_product_img2_remove_product_img3_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='photo',
            options={'verbose_name': 'Фото', 'verbose_name_plural': 'Фото'},
        ),
        migrations.AddField(
            model_name='photo',
            name='img',
            field=models.ImageField(default='None', upload_to='', verbose_name='Фото'),
        ),
    ]
