# Generated by Django 4.2.6 on 2023-11-29 02:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shopElectron', '0013_alter_photo_options_photo_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='img',
        ),
        migrations.AlterField(
            model_name='photo',
            name='img',
            field=models.ImageField(default='None', upload_to='upload/product', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='product',
            field=models.ForeignKey(default='None', on_delete=django.db.models.deletion.SET_DEFAULT, related_name='photos', to='shopElectron.product', verbose_name='Товар'),
        ),
    ]
