# Generated by Django 4.2.6 on 2023-12-13 04:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shopElectron', '0014_remove_product_img_alter_photo_img_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(default='None', max_length=50, verbose_name='ID_пользователя')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopElectron.product', verbose_name='ID товара товара')),
            ],
        ),
    ]
