# Generated by Django 4.2.6 on 2023-12-19 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopElectron', '0016_customers'),
    ]

    operations = [
        migrations.AddField(
            model_name='customers',
            name='date_brith',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата рождения'),
        ),
    ]
