# Generated by Django 4.2.6 on 2023-12-20 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopElectron', '0018_orders'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='summa',
            field=models.DecimalField(decimal_places=2, default='0', max_digits=5, verbose_name='Сумма'),
        ),
    ]
