# Generated by Django 4.2.6 on 2023-12-20 02:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopElectron', '0020_orders_suma_pokupki_orders_detail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='product',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='summa',
        ),
    ]
